#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend get-involved.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 307321-lb-01 100.26.254.6
        server 307321-web-02 52.3.249.59
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
